### ISSUE TITLE
How to use LRSLib.jl quietly?

### ISSUE THREAD

**Issue by shizejin** [JuliaPolyhedra/LRSLib.jl#15]
Hi @blegat, I am trying to use `Polyhedra.jl` combined with `LRSLib.jl` to do a lot of transformations from H representations to V representations. And thanks for your impressive works, they are very good to use.

One problem now I have is that the message "No feasible solution" is printed out every time there is no vertex found.

Here is a simple example:

```@julia
julia> A = [-1 0; 1 0]
2×2 Array{Int64,2}:
 -1  0
  1  0

julia> b = [-1, -1]
2-element Array{Int64,1}:
 -1
 -1

julia> H = SimpleHRepresentation(A, b)
H-representation
begin
 2 3 integer
 -1 1 0
 -1 -1 0
end

julia> H = LRSInequalityMatrix(H)
H-representation
begin
 2 3 rational
 -1//1 1//1 0//1
 -1//1 -1//1 0//1
end

julia> H = LRSMatrix(H)
H-representation
begin
 2 3 rational
 -1//1 1//1 0//1
 -1//1 -1//1 0//1
end

julia> V = LRSGeneratorMatrix(H)
 gmp v.6.1
No feasible solution
V-representation
begin
 0 3 rational
end
```

Because I am going to do this kind of procedure for thousands of times, it is really annoying. So I am wondering if there is any way to suppress this message?

This line comes from [here](https://github.com/JuliaPolyhedra/lrslib/blob/master/lrslib.c#L2168), and seems can be solved by defining an identifier `LRS_QUIET`. However, I could not figure out how to do this with Julia. 

I would appreciate a lot if you would like to help.

**Comment by blegat** [comment]
The release v0.1.2 is now quiet :)

**Comment by shizejin** [comment]
Thanks so much for your quick and impressive help! :)
