### ISSUE TITLE
Mac OS and Windows support

### ISSUE THREAD

**Issue by blegat** [JuliaPolyhedra/LRSLib.jl#2]
Mac OS support is still missing because there is only a simple `Makefile` in `lrslib` instead of a `configure` file that generates it. Windows support is missing because there is no lrslib package in [this repo](https://build.opensuse.org/project/show/windows:mingw:win32) and there need to be one containing the changes I made to lrslib in my fork.

Jan Engelhardt (@jengelh) has made a patch for `lrslib` to make it use GNU automake [here](https://build.opensuse.org/package/show/science/lrslib).
I have submitted the changes of the lrslib fork up to [this commit](https://github.com/blegat/lrslib/commit/89bf29524143836a298e3f7f513e8b96d6356031) (which is currently master) to David Avis to make it mainstream.

The plan to finish Linux support is as follows:
- [ ] once David Avis has released the first round of changes, use the upstream version for Linux build.

The plan for adding Mac OS support is as follows:
- [ ] apply Jan Engelhardt's patch to the [lrslib fork](https://github.com/blegat/lrslib)
- [ ] use the fork version for Mac OS build
- [ ] once David Avis has released the first round of changes, suggest to add Jan Engelhardt's patch
- [ ] once he has released them, use the mainstream version for Mac OS

The plan for adding Windows support is as follows:
- [ ] once David Avis has release the first round of changes, bump the version number used [here](https://build.opensuse.org/package/show/home:jengelh:dev/lrslib)
- [ ] from this build, make a Windows cross compilation build and submit it to [this repo](https://build.opensuse.org/project/show/windows:mingw:win32)
- [ ] Use this with [WinRPM](https://github.com/JuliaPackaging/WinRPM.jl)

**Comment by blegat** [comment]
@oyamad I see you are trying to add Mac OS support, thanks a lot !
How is it working ? Have you tried Jan Engelhardt's patch ?

**Comment by jengelh** [comment]
Let me point to https://build.opensuse.org/package/show/science/lrslib instead, because OBS home dirs are subject to cleanups (…aaaaaand it's gone).

**Comment by oyamad** [comment]
@blegat Something has compiled, but it is incomplete. Some tests by `Pkg.test("LRSLib")` fail (but some pass). Specifically, `Permutahedron` tests fail with `InexactError()`.

Here are diffs:

* [makefile.osx](https://github.com/oyamad/lrslib/commit/4bb57b5aac78deb1e9a25edf81bea16f5611596c)
* [deps/build.jl](https://github.com/oyamad/LRSLib.jl/commit/8ffe4c87afc0a443528dde059f4a81831308a395)

I am away this weekend. I will post detailed error messages next week if necessary. I will try to look into Jan Engelhardt's patch then.

It will be great if Mac OS (and Windows) is supported. Especially, I would like to use `lrsnash`, from the library [`Games.jl`](https://github.com/QuantEcon/Games.jl).

**Comment by blegat** [comment]
Could you give me more details on the `InexactError()` ?

**Comment by oyamad** [comment]
@blegat [Here](http://nbviewer.jupyter.org/gist/oyamad/aca7ab8c93c299041631ddd2f1552663) is a notebook with error messages. At least `detecthlinearities!` is failing.

Please let me know if you need more information.

**Comment by blegat** [comment]
@oyamad Thanks for the notebook. I don't see what is causing an `InexactError` at line 40 of `conversion.jl`, could you dig down the conversion that is causing the failure ? Is it in `convertoutput` ?
For the last issue `AssertionError: ispoint == zero(Rational{BigInt}) || ispoint == one(Rational{BigInt})`, could you give me what is printed if you add
```
if !(ispoint == zero(Rational{BigInt}) || ispoint == one(Rational{BigInt}))
    @show ispoint
end
```
just before the `@assert` ?

**Comment by oyamad** [comment]
`ispoint = -2//1` is the output of `@show ispoint`:

```jl
julia> using Polyhedra

julia> using LRSLib

julia> lib = LRSLibrary();

julia> A = [1 1 1; 1 0 0; 0 1 0; 0 0 1; -1 0 0; 0 -1 0; 0 0 -1];

julia> b = [6, 3, 3, 3, -1, -1, -1];

julia> linset = IntSet([1]);

julia> V = [2 3 1; 1 3 2; 3 1 2; 3 2 1; 2 1 3; 1 2 3];

julia> ine = SimpleHRepresentation(A, b, linset);

julia> poly = polyhedron(ine, lib);

julia> detecthlinearities!(poly)
ERROR: InexactError()
 in schedule_and_wait(::Task, ::Void) at ./event.jl:110
 in consume(::Task) at ./task.jl:269
 in done at ./task.jl:274 [inlined]
 in enumtomat(::LRSLib.LRSGeneratorMatrix{3}) at /Users/oyama/.julia/v0.5/LRSLib/src/conversion.jl:40
 in convert(::Type{Polyhedra.LiftedHRepresentation{3,Rational{BigInt}}}, ::LRSLib.LRSGeneratorMatrix{3}) at /Users/oyama/.julia/v0.5/LRSLib/src/conversion.jl:48
 in getine(::LRSLib.LRSPolyhedron{3}) at /Users/oyama/.julia/v0.5/LRSLib/src/polyhedron.jl:43
 in detecthlinearities!(::LRSLib.LRSPolyhedron{3}) at /Users/oyama/.julia/v0.5/LRSLib/src/polyhedron.jl:154

julia> LRSLib.getextm(poly, :Fresh)
V-representation
begin
 6 4 rational
ispoint = -2//1
Error showing value of type LRSLib.LRSGeneratorMatrix{3}:
ERROR: AssertionError: ispoint == zero(Rational{BigInt}) || ispoint == one(Rational{BigInt})
 in extractrow(::LRSLib.LRSGeneratorMatrix{3}, ::Int64) at /Users/oyama/.julia/v0.5/LRSLib/src/matrix.jl:269
 in nextvrep(::LRSLib.LRSGeneratorMatrix{3}, ::Int64) at /Users/oyama/.julia/v0.5/LRSLib/src/matrix.jl:208
 in next(::Polyhedra.VRepIterator{3,Rational{BigInt},3,Rational{BigInt}}, ::Tuple{Int64,Int64}) at /Users/oyama/.julia/v0.5/Polyhedra/src/representation.jl:109
 in show(::IOContext{Base.Terminals.TTYTerminal}, ::LRSLib.LRSGeneratorMatrix{3}) at /Users/oyama/.julia/v0.5/Polyhedra/src/show.jl:38
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::LRSLib.LRSGeneratorMatrix{3}) at ./REPL.jl:132
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::LRSLib.LRSGeneratorMatrix{3}) at ./REPL.jl:135
 in display(::LRSLib.LRSGeneratorMatrix{3}) at ./multimedia.jl:143
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:154
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:139
 in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:652
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1579
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:903
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##930#931) at ./REPL.jl:188
 in _start() at ./client.jl:360
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
```

Regarding conversion, what shall I check?

**Comment by blegat** [comment]
You shall check what is the `convert` call that throws the `InexactError`, what is the value being converted, in what time and where.
You can add a few `@show` statements in `convertoutput`, `getsolution`, `generatorproducer`, ... to help you find where it is thrown from.

**Comment by oyamad** [comment]
Adding `@show` to `M = [M; output']` in `conversion.jl` doesn't work, leading to `Segmentation fault: 11`. Maybe I will try to look into details tomorrow..

**Comment by oyamad** [comment]
Just to report, I changed the build script (https://github.com/oyamad/LRSLib.jl/commit/960da630114107a54ba6d6a772274170147f4d0b), and now `Permutahedron tests` pass whereas `Board tests` fail with `Segmentation fault: 11` ([notebook](https://gist.github.com/oyamad/aca7ab8c93c299041631ddd2f1552663#file-test_lrslib_2-ipynb)). It may be that compilation is failing itself.

**Comment by oyamad** [comment]
What is [this `while` loop](https://github.com/blegat/LRSLib.jl/blob/master/src/conversion.jl#L25-L35) in `generatorproducer` doing? It seems that it falls into an infinite loop if `getnextbasis(m)` is `true`.

**Comment by blegat** [comment]
This is producing the rays one after the other, it should not get in an infinite loop. It correponds to lines `192` to line `211` of `lrslib.c` or line `86` to line `92` of `chdemo.c` of lrslib

**Comment by oyamad** [comment]
OK, thanks.

The kernel always dies at `for output in Task(() -> generatorproducer(m))` ([notebook](http://nbviewer.jupyter.org/gist/oyamad/aca7ab8c93c299041631ddd2f1552663/test_LRSLib_3.ipynb)). I wonder what is wrong here.
