### ISSUE TITLE
Is ccall to `lrs_init` in the LRSLib.jl file executed every time?

### ISSUE THREAD

**Issue by oyamad** [JuliaPolyhedra/LRSLib.jl#28]
Another question:

Is this command https://github.com/JuliaPolyhedra/LRSLib.jl/blob/5d819d4a52554dfd69ef26881ad59b15f191e0bd/src/LRSLib.jl#L29-L31 executed every time when `LRSLib` is imported?

Yes for sure when the package is recompiled, but it seems No upon the second time on:

```jl
julia> using LRSLib

julia> unsafe_load(cglobal((:lrs_ofp, LRSLib.liblrs), Ptr{Cvoid}))
Ptr{Nothing} @0x0000000000000000  # <- Null pointer?
```

**Comment by blegat** [comment]
Good point, I think it should be in an `__init__` function:
https://docs.julialang.org/en/v1/manual/modules/index.html
