### ISSUE TITLE
Homebrew failing on travis

### ISSUE THREAD

**Issue by blegat** [JuliaPolyhedra/LRSLib.jl#38]
Homebrew is failing on travis with the new Catalina version of osx. Not sure what we can do to fix it. The long-term solution is to move to BinaryBuilder and https://github.com/JuliaPackaging/Yggdrasil

**Comment by bzinberg** [comment]
As described in https://github.com/JuliaPackaging/Homebrew.jl/issues/271#issuecomment-805287919, compat caps for Homebrew.jl are now preventing me from being able to install packages that depend on LRSLib, even from non-OSX.  I'm working around it by using `Pkg.develop("Homebrew")` which bypasses the cap, but I think the compat issue makes this a higher-severity issue.

@blegat, do you have a sense of how much work this would take?  And if hypothetically it were free, would there be any other reason to wait to migrate?
